sudo: false
language: python
python:
  - "3.7-dev"
install:
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
script:
    - pytest --cov=maps
after_success: coveralls
